/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.NguoiDungDAO;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author minh
 */
public class DangKiView extends javax.swing.JFrame {

    private static final String EMAIL_PATTERN = "^\\w+([.-]?\\w+)*@\\w+([.-]?\\w+)*(\\.\\w{2,3})+$";
    private static final Pattern pattern = Pattern.compile(EMAIL_PATTERN);

    /**
     * Creates new form DangKiView
     */
    public DangKiView() {
        initComponents();
        this.setSize(500, 400);
        this.setLocation(600, 200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel_taiKhoan2 = new javax.swing.JLabel();
        jTextField_taiKhoanDangKi = new javax.swing.JTextField();
        jTextField_matKhauDangKi = new javax.swing.JTextField();
        jLabel_matKhau2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_emailDangKi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_soDienThoaiDangKi = new javax.swing.JTextField();
        jButton_DangKi = new javax.swing.JButton();
        jButton_DangKi1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 153, 255));
        jLabel2.setText("ĐĂNG KÍ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 17, 160, 27));

        jLabel_taiKhoan2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_taiKhoan2.setForeground(new java.awt.Color(51, 153, 255));
        jLabel_taiKhoan2.setText("Tài Khoản: ");
        getContentPane().add(jLabel_taiKhoan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 130, 29));

        jTextField_taiKhoanDangKi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField_taiKhoanDangKi, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 62, 195, 30));

        jTextField_matKhauDangKi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField_matKhauDangKi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_matKhauDangKiActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_matKhauDangKi, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 195, 30));

        jLabel_matKhau2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_matKhau2.setForeground(new java.awt.Color(51, 153, 255));
        jLabel_matKhau2.setText("Mật Khẩu:");
        getContentPane().add(jLabel_matKhau2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 130, 29));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 153, 255));
        jLabel4.setText("Email:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 130, 29));

        jTextField_emailDangKi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField_emailDangKi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_emailDangKiActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_emailDangKi, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 195, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 153, 255));
        jLabel5.setText("Số Điện Thoại:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 130, 29));

        jTextField_soDienThoaiDangKi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField_soDienThoaiDangKi, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 195, 30));

        jButton_DangKi.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton_DangKi.setForeground(new java.awt.Color(51, 153, 255));
        jButton_DangKi.setText("Đăng Kí");
        jButton_DangKi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DangKiActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_DangKi, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        jButton_DangKi1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton_DangKi1.setForeground(new java.awt.Color(51, 153, 255));
        jButton_DangKi1.setText("Quay về đăng nhập");
        jButton_DangKi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DangKi1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_DangKi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_matKhauDangKiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_matKhauDangKiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_matKhauDangKiActionPerformed

    private void jTextField_emailDangKiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_emailDangKiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_emailDangKiActionPerformed

    private void jButton_DangKi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DangKi1ActionPerformed
        // TODO add your handling code here:                                                    
        dispose();
        DangNhapView dangNhapView = new DangNhapView();
        dangNhapView.show();
    }//GEN-LAST:event_jButton_DangKi1ActionPerformed

    public static boolean isValidEmail(String email) {
        Matcher matcher = pattern.matcher(email);
        return matcher.matches();
    }
    private void jButton_DangKiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DangKiActionPerformed
        // TODO add your handling code here:

        String taiKhoan = jTextField_taiKhoanDangKi.getText();
        String matKhau = jTextField_matKhauDangKi.getText();
        String email = jTextField_emailDangKi.getText();
        if (!isValidEmail(email)) {
            System.out.println("Email khong hop le");
            JOptionPane.showMessageDialog(this, "Email không hợp lệ!");
            return;
        }
        String soDienThoai = jTextField_soDienThoaiDangKi.getText();
        if (!soDienThoai.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Mời nhập số cho số diện thoại!");
            return;
        }

        NguoiDungDAO nguoiDungDAO = new NguoiDungDAO();
        if (nguoiDungDAO.checkAccountExists(taiKhoan)) {
            System.out.println("Tai khoan da ton tai");
            JOptionPane.showMessageDialog(this, "Tài khoản đã tồn tại");
        } else {
            nguoiDungDAO.registerUser(taiKhoan, matKhau, email, soDienThoai);
            System.out.println("Dang ki thanh cong");
            JOptionPane.showMessageDialog(this, "Đăng kí thành công");
        }
    }//GEN-LAST:event_jButton_DangKiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangKiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangKiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangKiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangKiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangKiView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_DangKi;
    private javax.swing.JButton jButton_DangKi1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_matKhau2;
    private javax.swing.JLabel jLabel_taiKhoan2;
    private javax.swing.JTextField jTextField_emailDangKi;
    private javax.swing.JTextField jTextField_matKhauDangKi;
    private javax.swing.JTextField jTextField_soDienThoaiDangKi;
    private javax.swing.JTextField jTextField_taiKhoanDangKi;
    // End of variables declaration//GEN-END:variables
}
